### ISSUE TITLE
TODO-List

### ISSUE THREAD

**Issue by zMoooooritz** [zMoooooritz/dotfiles#3]
- [x] Place all aliases in ~/.aliases and include that file from zsh and bash
- [x] Clean up the zshrc
- [x] Improve the i3 config (mostly binds) see the link below for inspiration
- [x] Move all custom scripts into ~/.scripts or ~/.local/bin
- [x] Update the ~/.profile and set the PATH variable to the custom scripts
- [x] Improve the weather_bar.py script (maybe see the link below)
- [x] Clean up the scripts and remove those that are not anymore needed
- [x] Bring some improvements to the polybar (see the link below for inspiration)
- [x] Add files and commands to the dotfiles to auto start the ssh-agent on startup and load all keys

https://github.com/LukeSmithxyz/voidrice
